api:
  title: Wallet server
  description: A wrapper around Ethereum API. It exposes features as friendly HTTP endpoints and forwards them to a Parity server.

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/wallet_server_db?characterEncoding=UTF-8&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: wallet-service
    password: q1w2e3r4
    initialize: true
    driver-class-name: com.mysql.jdbc.Driver
    continue-on-error: false
    test-on-borrow: true
    validation-query: SELECT 1

flyway:
  user: flyway
  password: q1w2e3r4
  datasource:
    url: ${spring.datasource.url}
    username: ${flyway.user}
    password: ${flyway.password}
    driver-class-name: ${spring.datasource.driver-class-name}
    initialize: false
    continue-on-error: false
    test-on-borrow: true
    validation-query: SELECT 1